// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: category.sql

package models

import (
	"context"
)

const addCategory = `-- name: AddCategory :one
INSERT INTO Categories (Id, Name, Type)
VALUES (DEFAULT, $1, $2)
RETURNING id, name, type
`

func (q *Queries) AddCategory(ctx context.Context, name string, type_ int32) (Category, error) {
	row := q.db.QueryRowContext(ctx, addCategory, name, type_)
	var i Category
	err := row.Scan(&i.ID, &i.Name, &i.Type)
	return i, err
}
